- name: Install nginx
  apt:
    update_cache: yes
    name: nginx
    state: present
- name: Copy nginx config
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart nginx
- name: Start and enable service nginx
  service:
    name: nginx
    enabled: yes
    state: started