- name: Install docker pkgs
  apt:
    update_cache: yes
    pkg:
      - docker.io
      - python3-docker
    state: present
- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes